### ISSUE TITLE
Stack failed to create

### ISSUE THREAD

**Issue by zvezdan019** [CloudSnorkel/CloudWatch2S3#1]
First creation of the stack failed with output:
```javascript
Resource **** must be in ARN format or "*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: ******)
```
I've deleted stack and tried again and it passed.

**Comment by kichik** [comment]
Can you include a little more detail about the error? Which resource was it complaining about?

**Comment by kichik** [comment]
Please reopen if you have more information.
