### ISSUE TITLE
Lifecycle policy on logbucket

### ISSUE THREAD

**Issue by zaro0508** [CloudSnorkel/CloudWatch2S3#13]
It would be nice to setup a [lifecycle policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html) on the [logbucket in the main account](https://github.com/CloudSnorkel/CloudWatch2S3/blob/master/CloudWatch2S3.template#L459-L461)

**Comment by kichik** [comment]
This is potentially [not our bucket](https://github.com/CloudSnorkel/CloudWatch2S3/blob/cd66bb318b6de8b64ee57ec099eaa66ef6c1bd79/CloudWatch2S3.template#L163-L167) and we do have it as an output to be extended by another template. I feel like it would be better handled outside of this template so this template can remain focused on copying logs to S3. There are also so many options for lifecycle policies it would greatly expand the number of parameters.

**Comment by zaro0508** [comment]
ahh ok. that makes sense.
