### ISSUE TITLE
Set exports for CloudWatch2S3 outputs

### ISSUE THREAD

**Issue by zaro0508** [CloudSnorkel/CloudWatch2S3#17]
The `CloudWatch2S3-additional-account` template has some dependencies on resources created from the `CloudWatch2S3` template.  However the [Outputs in CloudWatch2S3](https://github.com/CloudSnorkel/CloudWatch2S3/blob/master/CloudWatch2S3.template#L140-L156) do not contain [exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) therefore it cannot be referenced across stacks.  It would be great if exports were defined for the Outputs.

**Comment by kichik** [comment]
That template is meant to be used in different accounts. You can't use stack exports across accounts.

**Comment by kichik** [comment]
Oh that's pretty cool. I never heard of that.
