### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MAGAMEN** [CloudSnorkel/CloudWatch2S3#19]
I got the error when running the additional template, does anyone have any ideas?
": "An error occurred (AccessDeniedException) when calling the PutSubscriptionFilter operation: User with accountId: 1287256XXXX is not authorized to perform: logs:PutSubscriptionFilter on resource: arn:aws:logs:us-east-1:0755119XXXX:destination:BucketBackupLogDestination",
  "errorType": "ClientError",

**Comment by kichik** [comment]
Sounds like the `AllowedAccounts` parameter on the main stack might have the wrong account id. Make sure it matches `1287256XXXX`.
