### ISSUE TITLE
Log Name in the s3 Bucket

### ISSUE THREAD

**Issue by mnsanfilippo** [CloudSnorkel/CloudWatch2S3#2]
Hello, i am using your template to save the logs, is there any way that the name in the s3bucket of the logs is the same name that the log group name?

**Comment by kichik** [comment]
Which log group? `DeliveryStreamLog`, the one that contains the history of the export? Or the log groups you export? Are you saying you want one bucket per exported log group?

If you just want to choose a bucket name, you'd have to modify the template and add the following on line 415:

```
    BucketName: foobar
```

If you want a bucket per log group, you'd have to create multiple copies of this stack, each with its own different log group prefix and target bucket. That might be very expensive. It might be possible to create multiple DeliveryStreams and then route each log group to a different one, but that's not a feature I intend to add at the moment.
