### ISSUE TITLE
Shipping logs to s3 frequency

### ISSUE THREAD

**Issue by zvezdan019** [CloudSnorkel/CloudWatch2S3#6]
Hello, is it possible to change shipping log frequency, since default is 300s and can be changed to 900s, I need logs shipment once per day. I could not find the way to fix this. Any chance to change that? Thanks.

**Comment by kichik** [comment]
Kinesis only supports up to 900. I don't think it's built for what you are looking for. You may want to consider a secondary processing step that collects daily logs into one file.

**Comment by zvezdan019** [comment]
Hey @kichik, could you please tell me more about "a secondary processing step" or some link where I can read about that?

**Comment by kichik** [comment]
You can find some good leads here:

https://www.reddit.com/r/aws/comments/95al33/how_can_i_merge_multiple_csv_files_in_s3_using/

You can also try something like [s3-concat](https://pypi.org/project/s3-concat/).
