### ISSUE TITLE
Delete CloudWatch logs after exporting to S3

### ISSUE THREAD

**Issue by moisesrodriguez** [CloudSnorkel/CloudWatch2S3#7]
Hey, 

I just implemented this application to export CloudWatch logs, but I've noticed that the CloudWatch logs are still in there and not deleted. My initial purpose is to offload the GBs I have in CloudWatch Logs to S3 for a cheaper storage, but I can see that it just exports without deleting them. Is there currently a params to enable to delete the CloudWatch Logs that are already exported?

**Comment by kichik** [comment]
You can set the retention time for the logs to something low so they get deleted soon after being added. That's a CloudWatch feature. It will work better than whatever we can implement on the ingestion side.
