### ISSUE TITLE
Export older CloudWatch Logs

### ISSUE THREAD

**Issue by moisesrodriguez** [CloudSnorkel/CloudWatch2S3#8]
I have about a year's long log of about 10 log groups for about 400 GB of logs, so far CloudWatch2S3 has been awesome and working, but only for new log entries. Is there a way to export older logs?

Thanks!

**Comment by kichik** [comment]
It's not a feature I currently plan to add. You can try the built-in export functionality for now. It will probably not be the exact same format, but it will do the trick.
